source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false
target 'Cohober' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod "yoga", :path => "#{rn_path}/ReactCommon/yoga"
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  # pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  # react-native-maps dependencies
  # pod 'react-native-maps', path: rn_maps_path
  # pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils'
  # pod 'Bolts'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
