source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'


target ‘Cohober’ do
  rn_path = “../node_modules/react-native”

  pod “yoga", :path => "#{rn_path}/ReactCommon/yoga"
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    
    if target.name == "React"
      target.remove_from_project
    end
  end
end